name: Audit Performance Site Distant

on: [push]

jobs:
  performance-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run Stress Test sur develop.steerai.autos
        run: |
          ./apache-jmeter-5.6.3/bin/jmeter -n -t test_surcharge_connexion.jmx -l results.jtl -Jnb_users=10

      - name: Archive Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results-distant
          path: results.jtl
